export default function TermsPage() {
  return (
    <div className="mx-auto max-w-4xl p-6 sm:p-8">
      <div className="prose prose-lg max-w-none">
        <h1 className="text-4xl font-bold mb-2 pt-18">Terms and Conditions</h1>
        <p className="text-muted-foreground mb-8">
          <strong>MenoLisa</strong>
          <br />
          Macura Solutions LLC
          <br />
          Last Updated: August 17, 2026
        </p>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">1. Acceptance of Terms</h2>
          <p>
            These Terms and Conditions (&quot;Terms&quot;) are a legally binding agreement between you (&quot;User,&quot; &quot;you,&quot; or &quot;your&quot;) and Macura Solutions LLC (&quot;Company,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) governing your access to and use of the MenoLisa application, website (menolisa.com), and related services (collectively, the &quot;Service&quot;).
          </p>
          <p>
            By creating an account, accessing, or using MenoLisa, you acknowledge that you have read, understood, and agree to be bound by these Terms and our Privacy Policy. If you do not agree, you may not access or use the Service.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">2. Description of Service</h2>
          <p>MenoLisa is an educational application that provides:</p>
          <ul>
            <li><strong>Symptom tracker</strong> — Log and track menopause/perimenopause-related symptoms (e.g., hot flashes, night sweats, fatigue, brain fog, mood swings, anxiety, headaches, joint pain, bloating, insomnia, weight gain, low libido, period), including severity, timing, triggers, and notes</li>
            <li><strong>Hydration tracking</strong> — Optional water intake</li>
            <li><strong>Personalized 8-week plan</strong> — An AI-generated plan of movement exercises, relaxation sessions, and daily nutrition/habit tasks (e.g., meals, hydration, supplements), built from your quiz answers and any physical limitations you tell us about, and adjusted week to week as you complete it</li>
            <li><strong>Rewards and achievements</strong> — XP, streaks, levels, and badges calculated automatically from the plan tasks and symptoms you log, to help you track consistency</li>
            <li><strong>Lisa (AI assistant)</strong> — An AI-powered chatbot that provides educational information and personalized insights based on your tracked data</li>
            <li><strong>Weekly insights and pattern analysis</strong> — Summaries of your data to help you spot patterns</li>
            <li><strong>Menopause Score</strong> — A non-clinical wellness indicator (0–100) calculated from the information you provide and track, to help you see change over time. It is not a medical measurement, diagnosis, or score</li>
            <li><strong>Health summary / doctor reports (&quot;What Lisa Noticed&quot;)</strong> — Downloadable summaries for you to share with healthcare providers</li>
            <li><strong>Lifestyle suggestions</strong> — General suggestions related to sleep, relaxation, breathing, journaling, and similar topics</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">3. Medical Disclaimer and Limitations</h2>

          <h3 className="text-xl font-semibold mb-3">3.1 Not a Medical Device; Informational Only</h3>
          <p className="font-semibold">MENOLISA IS NOT A MEDICAL DEVICE AND DOES NOT PROVIDE MEDICAL ADVICE, DIAGNOSIS, TREATMENT, OR CLINICAL RECOMMENDATIONS.</p>
          <p>The Service is for educational and informational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified healthcare provider with any questions about a medical condition. Never disregard professional medical advice or delay seeking it because of something you read or received through MenoLisa.</p>

          <h3 className="text-xl font-semibold mb-3 mt-6">3.2 No Diagnosis, Prescription, or Clinical Decision Support</h3>
          <p>We do not diagnose conditions, prescribe treatments, or provide clinical decision support. The content provided by Lisa and any reports or insights are for your information only and do not constitute medical recommendations.</p>

          <h3 className="text-xl font-semibold mb-3 mt-6">3.3 NOT for Medical Emergencies</h3>
          <p>MenoLisa is NOT for medical emergencies. If you think you have a medical emergency, call 911 (or your local emergency number) or go to the nearest emergency room immediately. Do not rely on the app for emergency care.</p>

          <h3 className="text-xl font-semibold mb-3 mt-6">3.4 AI-Generated Content Disclaimer</h3>
          <p>Responses from Lisa are generated by artificial intelligence (AI). While we strive for accuracy, AI-generated content may be incomplete, inaccurate, or outdated. You should not rely on Lisa&apos;s responses as a sole source of health information or as a substitute for professional medical advice. You are responsible for any decisions you make based on content from the Service.</p>

          <h3 className="text-xl font-semibold mb-3 mt-6">3.5 No Doctor-Patient Relationship</h3>
          <p>Use of MenoLisa does not create a doctor-patient or other healthcare provider relationship between you and Macura Solutions LLC or any of its employees, contractors, or affiliates.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">4. User Accounts and Registration</h2>
          <p>To use MenoLisa you must be at least 18 years old and have the legal capacity to enter into these Terms. You must provide accurate information when creating your account. You are responsible for maintaining the security of your email account used for sign-in (e.g., magic links) and for all activity under your account. Each user may maintain only one active account.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">5. User Responsibilities and Acceptable Use</h2>
          <p>You agree to use MenoLisa only for lawful purposes and in accordance with these Terms — as an educational tool and personal symptom tracker. You agree NOT to: use the Service for any illegal purpose; impersonate others; attempt unauthorized access to the Service or other accounts; interfere with or disrupt the Service; use bots or automated means without permission; upload malware; collect other users&apos; data; harass or harm others; reverse engineer or resell the Service; or share account credentials. You are solely responsible for content you submit (e.g., symptom logs, notes, chat messages) and must not violate any third-party rights or applicable laws.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">6. Health Data and Doctor Reports</h2>
          <p>Doctor reports and health summaries (&quot;What Lisa Noticed&quot;) are <strong>informational summaries</strong> of your tracked data. They are not medical documents, clinical reports, or substitutes for professional evaluation. You may choose to share them with your healthcare provider; any decisions you or your provider make based on the app or these reports are your responsibility. We do not guarantee the completeness or accuracy of these summaries.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">7. Subscription and Payment Terms</h2>

          <h3 className="text-xl font-semibold mb-3">7.1 Paid Subscription and Billing</h3>
          <p>Access to the service requires a paid subscription. There is no free trial: your payment method is charged in full at checkout, and the price and billing frequency are shown before you pay. By subscribing, you authorize us to charge your chosen payment method at the start of each billing period. Subscriptions automatically renew unless you cancel before the renewal date.</p>
          <p>All subscriptions are purchased and billed through our website (via Stripe), not through the Apple App Store or Google Play. If you use the MenoLisa mobile app, it is a free download: the app itself is not sold through in-app purchase, and no payment is processed by Apple or Google. You subscribe on menolisa.com and then sign in to the app with the same account to access your plan.</p>

          <h3 className="text-xl font-semibold mb-3 mt-6">7.2 Cancellation</h3>
          <p>You may cancel your subscription at any time via your account settings or by contacting us at <a href="mailto:support@macurasolutions.us" className="text-primary hover:underline">support@macurasolutions.us</a>. Cancellation takes effect at the end of the current billing period. You will retain access until then and will not be charged for subsequent periods.</p>

          <h3 className="text-xl font-semibold mb-3 mt-6">7.3 Refund Policy</h3>
          <p>We offer a 7-day refund from the date of your initial subscription purchase. To request a refund, contact us at <a href="mailto:support@macurasolutions.us" className="text-primary hover:underline">support@macurasolutions.us</a> within 7 days with the email on your account and purchase date. Refunds are only for the initial purchase, not renewals; we process approved refunds within 5–10 business days to the original payment method. Users who have already received a refund are not eligible for another. After a refund, your subscription is canceled and premium access ends.</p>

          <h3 className="text-xl font-semibold mb-3 mt-6">7.4 No In-App Purchases</h3>
          <p>MenoLisa does not sell subscriptions, or anything else, through Apple App Store or Google Play in-app purchase. Every subscription is purchased on our website and billed by Stripe, regardless of whether you register on the website or through the mobile app. The cancellation and refund terms in this section apply to every subscription — there is no separate Apple or Google billing relationship to manage.</p>

          <h3 className="text-xl font-semibold mb-3 mt-6">7.5 The 8-Week Guarantee</h3>
          <p>For eligible subscriptions purchased through our website, we offer an optional &quot;8-Week Guarantee.&quot; If you complete at least <strong>90% of your plan</strong> across eight (8) continuous weeks of paid subscription and you do not feel better, you may request a full refund of the amount you paid for that period.</p>
          <p><strong>How the 90% is measured.</strong> Your plan schedules a set of daily tasks for each of the eight weeks. Completion means those tasks were marked as done in the app. We calculate your figure as the number of scheduled tasks you marked complete during the eight-week period, divided by the number of tasks your plan scheduled for that same period. You do not need to submit evidence, screenshots, or a diary — the calculation uses the completion records already stored in your account. You may ask us for your figure at any time and we will provide it, along with how it was calculated.</p>
          <p><strong>What the condition is for.</strong> The guarantee covers the case where you followed the plan and it did not help you. It is not a general satisfaction refund; if you did not use the plan, the 90% threshold will not be met and this guarantee will not apply. The 7-day refund in Section 7.3 is separate and has no completion condition.</p>
          <p>The eight-week period must be completed while your subscription is paid and active. If you cancel or your subscription lapses before the eight weeks end, the period is incomplete and this guarantee does not apply, though Section 7.3 may still.</p>
          <p>MenoLisa is a <strong>wellness product, not a medical treatment.</strong> The Menopause Score and any insights in the app are non-clinical wellness indicators, not medical measurements, diagnoses, or guarantees of any health outcome. This guarantee is a refund promise only and does not promise any medical or clinical result. Whether you feel better is your own assessment and we will not ask you to justify it.</p>
          <p>To request, email <a href="mailto:support@macurasolutions.us" className="text-primary hover:underline">support@macurasolutions.us</a> within fourteen (14) days after your eight-week period ends, using the email on your account. This guarantee may be used once per user. It is in addition to the 7-day refund in Section 7.3; a user who has received any refund is not eligible for another. After a refund, your subscription is canceled and premium access ends.</p>
          <p>Nothing in this section limits any refund or cancellation right you have under the consumer law of your country or state, where such rights cannot be waived.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">8. Intellectual Property</h2>
          <p>MenoLisa (including design, features, content, and software) is owned by Macura Solutions LLC and protected by intellectual property laws. You may not copy, modify, distribute, or create derivative works without our written permission. You retain ownership of your content; you grant us a limited license to use, store, and process it to provide the Service. Feedback you provide may be used by us without obligation to compensate you.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">9. Limitation of Liability</h2>
          <p className="font-semibold">TO THE MAXIMUM EXTENT PERMITTED BY LAW, MACURA SOLUTIONS LLC AND ITS AFFILIATES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES (INCLUDING LOSS OF PROFITS, DATA, GOODWILL, OR PERSONAL INJURY) ARISING FROM YOUR USE OF THE SERVICE, RELIANCE ON ANY CONTENT, OR UNAUTHORIZED ACCESS TO YOUR DATA. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS BEFORE THE EVENT GIVING RISE TO LIABILITY, OR ONE HUNDRED DOLLARS ($100), WHICHEVER IS GREATER. Some jurisdictions do not allow these limitations; where prohibited, they may not apply to you.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">10. Indemnification</h2>
          <p>You agree to indemnify and hold harmless Macura Solutions LLC and its directors, officers, employees, agents, and affiliates from any claims, damages, losses, or expenses (including reasonable attorneys&apos; fees) arising from your use of the Service, violation of these Terms, violation of any third-party rights or laws, or content you submit.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">11. Termination</h2>
          <p>You may terminate your account at any time via app settings or by contacting us. We may suspend or terminate your access without prior notice for violation of these Terms, harmful conduct, non-payment, extended inactivity, or as required by law. Upon termination, your right to use the Service ends. Provisions that by their nature should survive (e.g., disclaimers, limitation of liability, indemnification) will survive. We may delete your data in accordance with our Privacy Policy.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">12. Governing Law and Dispute Resolution</h2>
          <p>These Terms are governed by the laws of the State of Delaware, United States, without regard to conflict of law principles. Any dispute shall first be addressed by contacting us at <a href="mailto:support@macurasolutions.us" className="text-primary hover:underline">support@macurasolutions.us</a> to seek informal resolution. If unresolved, disputes shall be resolved by binding arbitration administered by the American Arbitration Association under its Consumer Arbitration Rules, in the English language, in Delaware or remotely. You and we agree to resolve disputes on an individual basis only, not in a class, consolidated, or representative action. Either party may seek injunctive relief in court for intellectual property violations.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">13. Changes to Terms</h2>
          <p>We may modify these Terms at any time. We will update the &quot;Last Updated&quot; date and, for material changes, notify you via the app or email and give you an opportunity to review. Continued use after the effective date constitutes acceptance. If you do not agree, you must stop using the Service and cancel your subscription.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">14. Apple App Store Additional Terms</h2>
          <p>If you downloaded the app from the Apple App Store, the following additional terms apply and take precedence over any conflicting provision above with respect to Apple:</p>
          <ul>
            <li>This Agreement is between you and Macura Solutions LLC only, not with Apple Inc. (&quot;Apple&quot;), and Apple is not responsible for the Service or its content.</li>
            <li>The license granted to you is limited to a non-transferable license to use the app on any Apple-branded product that you own or control, as permitted by the Usage Rules in Apple&apos;s App Store Terms of Service.</li>
            <li>Apple has no obligation whatsoever to furnish any maintenance or support services with respect to the app. As between us and Apple, any such obligation, to the extent required under applicable law, is ours alone.</li>
            <li>Apple is not responsible for any product warranties, whether express or implied by law. In the event of any failure of the app to conform to any applicable warranty, you may notify Apple, and Apple will refund the purchase price for the app to you, if any; to the maximum extent permitted by applicable law, Apple has no other warranty obligation whatsoever with respect to the app, and any other claims, losses, liabilities, damages, costs, or expenses attributable to a failure to conform to a warranty are our sole responsibility.</li>
            <li>We, not Apple, are responsible for addressing any claims by you or any third party relating to the app or your possession and/or use of the app, including: (i) product liability claims; (ii) any claim that the app fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection or similar legislation.</li>
            <li>In the event of any third-party claim that the app, or your possession and use of it, infringes that third party&apos;s intellectual property rights, we, not Apple, will be solely responsible for the investigation, defense, settlement, and discharge of any such claim.</li>
            <li>You represent and warrant that you are not located in a country subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a &quot;terrorist supporting&quot; country, and that you are not listed on any U.S. Government list of prohibited or restricted parties.</li>
            <li>You must comply with any applicable third-party terms (e.g., your wireless data service agreement) when using the app.</li>
            <li>Apple and Apple&apos;s subsidiaries are third-party beneficiaries of this Agreement, and upon your acceptance of these Terms, Apple will have the right (and will be deemed to have accepted the right) to enforce this Agreement against you as a third-party beneficiary of it.</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">15. Contact Information</h2>
          <p>For questions about these Terms:</p>
          <p>
            <strong>Macura Solutions LLC</strong>
            <br />
            30 N Gould St, Ste N, Sheridan, WY 82801, United States
            <br />
            Email: <a href="mailto:support@macurasolutions.us" className="text-primary hover:underline">support@macurasolutions.us</a>
          </p>
        </section>

        <section className="mb-8 p-6 bg-muted rounded-lg">
          <h2 className="text-2xl font-semibold mb-4">Acknowledgment</h2>
          <p className="font-semibold">
            BY CREATING AN ACCOUNT OR USING MENOLISA, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS AND CONDITIONS AND OUR PRIVACY POLICY.
          </p>
        </section>
      </div>
    </div>
  );
}
