export default function TermsPage() {
  return (
    <div className="mx-auto max-w-4xl p-6 sm:p-8">
      <div className="prose prose-lg max-w-none">
        <h1 className="text-4xl font-bold mb-2 pt-18">Terms and Conditions</h1>
        <p className="text-muted-foreground mb-8">
          <strong>MenoLisa</strong>
          <br />
          Macura Solutions LLC
          <br />
          Last Updated: March 10, 2026
        </p>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">1. Acceptance of Terms</h2>
          <p>
            These Terms and Conditions (&quot;Terms&quot;) are a legally binding agreement between you (&quot;User,&quot; &quot;you,&quot; or &quot;your&quot;) and Macura Solutions LLC (&quot;Company,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) governing your access to and use of the MenoLisa application, website (menolisa.com), and related services (collectively, the &quot;Service&quot;).
          </p>
          <p>
            By creating an account, accessing, or using MenoLisa, you acknowledge that you have read, understood, and agree to be bound by these Terms and our Privacy Policy. If you do not agree, you may not access or use the Service.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">2. Description of Service</h2>
          <p>MenoLisa is an educational application that provides:</p>
          <ul>
            <li><strong>Symptom tracker</strong> — Log and track menopause/perimenopause-related symptoms (e.g., hot flashes, night sweats, fatigue, brain fog, mood swings, anxiety, headaches, joint pain, bloating, insomnia, weight gain, low libido, period), including severity, timing, triggers, and notes</li>
            <li><strong>Mood and hydration tracking</strong> — Daily mood ratings and optional water intake</li>
            <li><strong>Lisa (AI assistant)</strong> — An AI-powered chatbot that provides educational information and personalized insights based on your tracked data</li>
            <li><strong>Weekly insights and pattern analysis</strong> — Summaries of your data to help you spot patterns</li>
            <li><strong>Health summary / doctor reports (&quot;What Lisa Noticed&quot;)</strong> — Downloadable summaries for you to share with healthcare providers</li>
            <li><strong>Lifestyle suggestions</strong> — General suggestions related to sleep, relaxation, breathing, journaling, and similar topics</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">3. Medical Disclaimer and Limitations</h2>

          <h3 className="text-xl font-semibold mb-3">3.1 Not a Medical Device; Informational Only</h3>
          <p className="font-semibold">MENOLISA IS NOT A MEDICAL DEVICE AND DOES NOT PROVIDE MEDICAL ADVICE, DIAGNOSIS, TREATMENT, OR CLINICAL RECOMMENDATIONS.</p>
          <p>The Service is for educational and informational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified healthcare provider with any questions about a medical condition. Never disregard professional medical advice or delay seeking it because of something you read or received through MenoLisa.</p>

          <h3 className="text-xl font-semibold mb-3 mt-6">3.2 No Diagnosis, Prescription, or Clinical Decision Support</h3>
          <p>We do not diagnose conditions, prescribe treatments, or provide clinical decision support. The content provided by Lisa and any reports or insights are for your information only and do not constitute medical recommendations.</p>

          <h3 className="text-xl font-semibold mb-3 mt-6">3.3 NOT for Medical Emergencies</h3>
          <p>MenoLisa is NOT for medical emergencies. If you think you have a medical emergency, call 911 (or your local emergency number) or go to the nearest emergency room immediately. Do not rely on the app for emergency care.</p>

          <h3 className="text-xl font-semibold mb-3 mt-6">3.4 AI-Generated Content Disclaimer</h3>
          <p>Responses from Lisa are generated by artificial intelligence (AI). While we strive for accuracy, AI-generated content may be incomplete, inaccurate, or outdated. You should not rely on Lisa&apos;s responses as a sole source of health information or as a substitute for professional medical advice. You are responsible for any decisions you make based on content from the Service.</p>

          <h3 className="text-xl font-semibold mb-3 mt-6">3.5 No Doctor-Patient Relationship</h3>
          <p>Use of MenoLisa does not create a doctor-patient or other healthcare provider relationship between you and Macura Solutions LLC or any of its employees, contractors, or affiliates.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">4. User Accounts and Registration</h2>
          <p>To use MenoLisa you must be at least 18 years old and have the legal capacity to enter into these Terms. You must provide accurate information when creating your account. You are responsible for maintaining the security of your email account used for sign-in (e.g., magic links) and for all activity under your account. Each user may maintain only one active account.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">5. User Responsibilities and Acceptable Use</h2>
          <p>You agree to use MenoLisa only for lawful purposes and in accordance with these Terms — as an educational tool and personal symptom tracker. You agree NOT to: use the Service for any illegal purpose; impersonate others; attempt unauthorized access to the Service or other accounts; interfere with or disrupt the Service; use bots or automated means without permission; upload malware; collect other users&apos; data; harass or harm others; reverse engineer or resell the Service; or share account credentials. You are solely responsible for content you submit (e.g., symptom logs, notes, chat messages) and must not violate any third-party rights or applicable laws.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">6. Health Data and Doctor Reports</h2>
          <p>Doctor reports and health summaries (&quot;What Lisa Noticed&quot;) are <strong>informational summaries</strong> of your tracked data. They are not medical documents, clinical reports, or substitutes for professional evaluation. You may choose to share them with your healthcare provider; any decisions you or your provider make based on the app or these reports are your responsibility. We do not guarantee the completeness or accuracy of these summaries.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">7. Subscription and Payment Terms</h2>

          <h3 className="text-xl font-semibold mb-3">7.1 Free Trial</h3>
          <p>We may offer a free trial with full access to features. Trial duration and terms will be shown at registration. You may receive reminders before the trial ends.</p>

          <h3 className="text-xl font-semibold mb-3 mt-6">7.2 Paid Subscription and Billing</h3>
          <p>After the trial, continued access may require a paid subscription. Pricing and billing frequency will be clearly shown before payment. By subscribing, you authorize us to charge your chosen payment method at the start of each billing period. Subscriptions automatically renew unless you cancel before the renewal date.</p>

          <h3 className="text-xl font-semibold mb-3 mt-6">7.3 Cancellation</h3>
          <p>You may cancel your subscription at any time via your account settings or by contacting us at <a href="mailto:support@macurasolutions.us" className="text-primary hover:underline">support@macurasolutions.us</a>. Cancellation takes effect at the end of the current billing period. You will retain access until then and will not be charged for subsequent periods.</p>

          <h3 className="text-xl font-semibold mb-3 mt-6">7.4 Refund Policy</h3>
          <p>We offer a 7-day refund from the date of your initial subscription purchase. To request a refund, contact us at <a href="mailto:support@macurasolutions.us" className="text-primary hover:underline">support@macurasolutions.us</a> within 7 days with the email on your account and purchase date. Refunds are only for the initial purchase, not renewals; we process approved refunds within 5–10 business days to the original payment method. Users who have already received a refund are not eligible for another. After a refund, your subscription is canceled and premium access ends.</p>

          <h3 className="text-xl font-semibold mb-3 mt-6">7.5 Platform-Specific Billing (Apple / Google)</h3>
          <p>If you subscribe through the Apple App Store or Google Play, payment is processed by Apple or Google under their respective terms. Cancellation and refunds for those purchases may be managed through your Apple or Google account settings and are subject to Apple&apos;s and Google&apos;s policies. For subscriptions made through our website (e.g., Stripe), the cancellation and refund terms in this section apply.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">8. Intellectual Property</h2>
          <p>MenoLisa (including design, features, content, and software) is owned by Macura Solutions LLC and protected by intellectual property laws. You may not copy, modify, distribute, or create derivative works without our written permission. You retain ownership of your content; you grant us a limited license to use, store, and process it to provide the Service. Feedback you provide may be used by us without obligation to compensate you.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">9. Limitation of Liability</h2>
          <p className="font-semibold">TO THE MAXIMUM EXTENT PERMITTED BY LAW, MACURA SOLUTIONS LLC AND ITS AFFILIATES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES (INCLUDING LOSS OF PROFITS, DATA, GOODWILL, OR PERSONAL INJURY) ARISING FROM YOUR USE OF THE SERVICE, RELIANCE ON ANY CONTENT, OR UNAUTHORIZED ACCESS TO YOUR DATA. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS BEFORE THE EVENT GIVING RISE TO LIABILITY, OR ONE HUNDRED DOLLARS ($100), WHICHEVER IS GREATER. Some jurisdictions do not allow these limitations; where prohibited, they may not apply to you.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">10. Indemnification</h2>
          <p>You agree to indemnify and hold harmless Macura Solutions LLC and its directors, officers, employees, agents, and affiliates from any claims, damages, losses, or expenses (including reasonable attorneys&apos; fees) arising from your use of the Service, violation of these Terms, violation of any third-party rights or laws, or content you submit.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">11. Termination</h2>
          <p>You may terminate your account at any time via app settings or by contacting us. We may suspend or terminate your access without prior notice for violation of these Terms, harmful conduct, non-payment, extended inactivity, or as required by law. Upon termination, your right to use the Service ends. Provisions that by their nature should survive (e.g., disclaimers, limitation of liability, indemnification) will survive. We may delete your data in accordance with our Privacy Policy.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">12. Governing Law and Dispute Resolution</h2>
          <p>These Terms are governed by the laws of the State of Delaware, United States, without regard to conflict of law principles. Any dispute shall first be addressed by contacting us at <a href="mailto:support@macurasolutions.us" className="text-primary hover:underline">support@macurasolutions.us</a> to seek informal resolution. If unresolved, disputes shall be resolved by binding arbitration administered by the American Arbitration Association under its Consumer Arbitration Rules, in the English language, in Delaware or remotely. You and we agree to resolve disputes on an individual basis only, not in a class, consolidated, or representative action. Either party may seek injunctive relief in court for intellectual property violations.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">13. Changes to Terms</h2>
          <p>We may modify these Terms at any time. We will update the &quot;Last Updated&quot; date and, for material changes, notify you via the app or email and give you an opportunity to review. Continued use after the effective date constitutes acceptance. If you do not agree, you must stop using the Service and cancel your subscription.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">14. Contact Information</h2>
          <p>For questions about these Terms:</p>
          <p>
            <strong>Macura Solutions LLC</strong>
            <br />
            30 N Gould St, Ste N, Sheridan, WY 82801, United States
            <br />
            Email: <a href="mailto:support@macurasolutions.us" className="text-primary hover:underline">support@macurasolutions.us</a>
          </p>
        </section>

        <section className="mb-8 p-6 bg-muted rounded-lg">
          <h2 className="text-2xl font-semibold mb-4">Acknowledgment</h2>
          <p className="font-semibold">
            BY CREATING AN ACCOUNT OR USING MENOLISA, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS AND CONDITIONS AND OUR PRIVACY POLICY.
          </p>
        </section>
      </div>
    </div>
  );
}
